spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/DigitalMedia
        registration:
          keycloak:
            client-id: microservicios
            client-secret: pe6zKFxXCjMZnVaJm7T3N7i4gCzpPXgH
            scope: openid
            redirect_uri: http://localhost:8081/login/oauth2/code/google

keycloak:
  realm: DigitalMedia
  serverUrl: http://localhost:8080
  clientId: microservicios
  clientSecret: pe6zKFxXCjMZnVaJm7T3N7i4gCzpPXgH

server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    instance-id: user-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
